Add key to remove error
bejamas/gatsby-plugin-csp pull request #23
Opened 2021-11-09 18:26 UTC by Primajin

fixes #13

```

 ERROR

Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <head>. See https://reactjs.org/link/warning-keys for more information.
    at meta
    at HTML (R:\eyesbound\.cache\page-ssr\routes\render-page.js
```

2022-01-11 03:02 UTC, w3bdesign approved these changes

2022-01-22 16:36 UTC, Primajin commented
Thanks @w3bdesign for approving the changes. Do you think we can merge this soon~ish?

2022-01-22 18:44 UTC, w3bdesign commented
> Thanks @w3bdesign for approving the changes. Do you think we can merge this soon~ish?

Yes, we can merge.

Just need approval from someone with write access.
@Primajin

2022-01-22 21:36 UTC, w3bdesign requested changes
Would it be better to use import instead of require, and const instead of let?

2022-01-22 21:36 UTC, w3bdesign commented
@Primajin

2022-01-23 07:16 UTC, Primajin commented
I am happy helping transforming this from common JS into a module (ESM `import` vs. CJS `require`).
However this could be considered a breaking change and I highly recommend doing this in a separate PR with a proper plan and discussion 😅

Let's keep the diff of this PR here small as it's sole purpose was fixing the error with the missing key, happy to file other PRs for chore (`let` vs. `const` etc.) if applicable.

2022-01-23 11:08 UTC, w3bdesign approved these changes

2022-01-23 11:08 UTC, w3bdesign approved these changes

2022-11-07 06:58 UTC, Primajin commented
Hey @thomkrupa @sweaverdeloitte do you have write access to this repo? This is a pretty small diff and many people are affected by the bug, can we go forward with this? Would be great, thank you!

2022-11-11 22:07 UTC, thomkrupa approved these changes

2022-11-11 22:07 UTC, merged

2022-11-11 22:16 UTC, thomkrupa commented
Thank you @Primajin! Merged. We're planning a bigger update to the plugin soon!

2022-11-11 22:31 UTC, Primajin commented
Sweet, looking forward to. Let me know if you need any support